ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- 오라클 계정 생성
CREATE USER jobboard IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE, DBA TO jobboard;
SELECT * FROM SYS.ALL_USERS WHERE USERNAME = UPPER('jobboard');

-- 오라클 계정 삭제
REVOKE CONNECT, RESOURCE, DBA FROM jobboard;
DROP USER jobboard CASCADE;