-- 오라클 계정 생성
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER jobboard IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE, DBA TO jobboard;
REVOKE CONNECT FROM jobboard;

-- 오라클 계정 삭제
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
DROP USER jobboard CASCADE;